### PR TITLE
Added new identifier support for stereo cameras

### LINKED ISSUE #21: Improve blender stereo camera handling
Blender has [naming conventions](https://www.blender.org/manual/rigging/armatures/editing/properties.html#naming-conventions) for right and left objects that is used for armatures. We already have support for the "name.left" and "name.right" formats by the looks of the code, but I would propose we take it a step further and implement the naming conventions linked above. This will help provide continuity with Blender and may be more familiar to Blender artists. It should be fairly straightforward to implement a regex script that matches these patterns.

### PR DESCRIPTION
**Pull request by scribblemaniac**
It should support all of the Blender naming conventions now in addition to the old 'left' and 'right' camera names.

Closes #21

### CODE REVIEW

**Comment by morevnaproject** [comment]
I need some time for testing this on the latest Blender. Thank you! ^__^

**Comment by scribblemaniac** [comment]
No problem, go for it! ^_^

**Comment by morevnaproject** [comment]
Hello! It doesn't work with my old files. Probably because my rig uses ".Left" and ".Right" suffixes. ^__^

Sample file -     http://cloud.morevnaproject.org/seafile/f/36f7f6e1be/?raw=1

**Comment by scribblemaniac** [comment]
Ah, it's actually the middle camera `d-cam-01` that's causing the issue. I'll fix this soon.

**Comment by scribblemaniac** [comment]
@morevnaproject Updated! I fixed that issue and did a bit of refactoring/optimization. Should be good to go now. Do you want me to add something in the docs about ordering for this?

**Comment by morevnaproject** [comment]
@scribblemaniac I have tested and now it works perfectly! I did a merge and also added the possibility to render using native  stereo multiview. ^__^

About the docs - this would be much appreciated! But where to put them? Currently I have several documentation-related pages on MorevnaProject website - https://morevnaproject.org/renderchan/documentation/

But I think this is not the best approach if in a long-term perspective, because I would like to have some mechanism to quickly update illustrations and to other maintaining routines, also keeping it open for other contributors. I suspect ReadTheDocs could be a good option for us - https://read-the-docs.readthedocs.org/en/latest/getting_started.html#import-docs

But for now this is how it is. I will be happy to create an account for you at morevnaproject.org with write permissions, if you are willing to write a few lines about stereo 3D in RenderChan. ^___^

**Comment by scribblemaniac** [comment]
Yes a write access account with morevnaproject.org seems like it will work well for the short term. For the long term, I would probably recommend Github Pages. Read The Docs is good if we're going with something like Sphinx and you want to add API documentation, but from what I gather it does not look too useful for user-oriented documentation and probably wouldn't allow the same level of flexibility that Github Pages does.

**Comment by morevnaproject** [comment]
OK, then I need to know your email to create an account. Please submit a request here - https://morevnaproject.org/about/contact/. Make sure to put some random text in the "Message" field. Then, create an issue at https://github.com/morevnaproject/RenderChan/issues and put the same random text as issue description. In this case I will know that request is really submitted by you. ^__^

**Comment by scribblemaniac** [comment]
I think it should suffice just to put the message here rather than making a completely new issue.
The message text is: `CVx7TS8HdDjVX26MMvjh`

Feel free to contact me through that email address if the need arises. It's my personal email so I don't like to have it public for spam and privacy reasons.

**Comment by morevnaproject** [comment]
>  just don't like to have it public for spam and privacy reasons
Yeah, that's exactly why I have asked to submit a private request. ^__^

Welcome onboard! ^__^

**Comment by scribblemaniac** [comment]
Thank you very much ^_^

**Pull request closed without merging**
